armor:
  standPose:
    1:
      bodyPose: [0, 0, 0]
      headPose: [0, 0, 0]
      LeftLegPose: [0, 0, 0]
      RightLegPose: [0, 0, 0]
      LeftArmPose: [339, 0, 346]
      RightArmPose: [339, 0, 15]
    2:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 0, 0, 0 ]
      LeftLegPose: [ 0, 0, 0 ]
      RightLegPose: [ 0, 0, 0 ]
      LeftArmPose: [ 0, 0, 0 ]
      RightArmPose: [ 0, 0, 0 ]
    3:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 14, 0, 0 ]
      LeftLegPose: [ 0, 0, 0 ]
      RightLegPose: [ 0, 0, 0 ]
      LeftArmPose: [ 312, 0, 39 ]
      RightArmPose: [ 312, 0, 323 ]
    4:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 356, 0, 0 ]
      LeftLegPose: [ 0, 0, 0 ]
      RightLegPose: [ 0, 0, 0 ]
      LeftArmPose: [ 0, 0, 343 ]
      RightArmPose: [ 282, 0, 0 ]
    5:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 346, 0, 0 ]
      LeftLegPose: [ 11, 0, 353 ]
      RightLegPose: [ 0, 0, 8 ]
      LeftArmPose: [ 31, 0, 353 ]
      RightArmPose: [ 248, 37, 0 ]
    6:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 346, 0, 0 ]
      LeftLegPose: [ 11, 0, 353 ]
      RightLegPose: [ 0, 0, 8 ]
      LeftArmPose: [ 254, 37, 0 ]
      RightArmPose: [ 254, 324, 0 ]
    7:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 346, 0, 0 ]
      LeftLegPose: [ 11, 0, 353 ]
      RightLegPose: [ 0, 0, 8 ]
      LeftArmPose: [ 254, 341, 0 ]
      RightArmPose: [ 241, 40, 0 ]
    8:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 0, 0, 0 ]
      LeftLegPose: [ 0, 0, 0 ]
      RightLegPose: [ 0, 0, 0 ]
      LeftArmPose: [ 0, 0, 346 ]
      RightArmPose: [ 309, 338, 15 ]
    9:
      bodyPose: [ 0, 6, 0 ]
      headPose: [ 356, 47, 0 ]
      LeftLegPose: [ 0, 40, 350 ]
      RightLegPose: [ 0, 304, 0 ]
      LeftArmPose: [ 18, 0, 353 ]
      RightArmPose: [ 248, 47, 0 ]
    10:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 14, 23, 0 ]
      LeftLegPose: [ 18, 141, 350 ]
      RightLegPose: [ 349, 108, 0 ]
      LeftArmPose: [ 0, 0, 225 ]
      RightArmPose: [ 265, 334, 0 ]
    11:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 346, 348, 0 ]
      LeftLegPose: [ 0, 0, 353 ]
      RightLegPose: [ 315, 0, 0 ]
      LeftArmPose: [ 268, 13, 225 ]
      RightArmPose: [ 268, 348, 0 ]
    12:
      bodyPose: [ 0, 355, 0 ]
      headPose: [ 356, 30, 0 ]
      LeftLegPose: [ 238, 0, 306 ]
      RightLegPose: [ 349, 33, 343 ]
      LeftArmPose: [ 0, 0, 242 ]
      RightArmPose: [ 0, 0, 120 ]
    13:
      bodyPose: [ 0, 351, 0 ]
      headPose: [ 356, 324, 0 ]
      LeftLegPose: [ 346, 0, 12 ]
      RightLegPose: [ 248, 324, 343 ]
      LeftArmPose: [ 0, 0, 242 ]
      RightArmPose: [ 0, 0, 120 ]